### ISSUE TITLE
Need a plan about supporting Ingress v2 for kourier

### ISSUE THREAD

**Issue by ZhiminXiang** [knative-sandbox/net-ingressv2#14]
Currently Kourier configures the envoy directly by consuming Kingress. In the future after introducing Ingress v2, we need to think about how to make it work with Kourier before removing all Kingress from serving.

/cc @nak3

**Comment by markusthoemmes** [comment]
IMO, Kourier just becomes obsolete.

**Comment by ZhiminXiang** [comment]
That could be an option if we don't have a plan to make Kourier support ingress v2.
