### ISSUE TITLE
Missing steps in DEVELOPMENT.MD?

### ISSUE THREAD

**Issue by XanderStrike** [knative-sandbox/net-ingressv2#50]
When trying to kick the tires on this project, I've followed the instructions found in [DEVELOPMENT.MD](https://github.com/knative-sandbox/net-ingressv2/blob/main/DEVELOPMENT.md).

When following these instructions, I expect to end up with a working knative using the ingressv2 apis, presumably by installing some sort of net-ingressv2 controller.

However, I observe that no controller is installed. I get errors on the last step (`ko apply -f test/config/ -f config/`) that `config/` does not exist (it was removed in #10). When I create an empty directory there the command succeeds, but nothing is installed since the directory is empty.

I'm assuming there's some command to create and populate `config/`, but it's not in the documents that I can find. `go build` doesn't work so I don't think it's that.

**Comment by nak3** [comment]
Hi @XanderStrike
Thank you for this report.
Sorry, DEVELOPMENT.md is outdated and this repo does not host controller
but only conformance tests against Gateway API resources.

I am updating the docs now https://github.com/knative-sandbox/net-ingressv2/pull/51

**Comment by XanderStrike** [comment]
Hey @nak3 maybe I'm confused about the purpose of DEVELOPMENT.md and this repo.

I am hoping to follow steps to get a cluster with a working Knative serving that is writing Gateway APIs.

I'm hoping for something like the [net-kourier](https://github.com/knative-sandbox/net-kourier#getting-started) or [net-istio](https://github.com/knative-sandbox/net-istio/blob/main/DEVELOPMENT.md#install-istio) docs, or maybe a tab in the [Installing Knative Serving](https://knative.dev/docs/install/install-serving-with-yaml/#install-a-networking-layer) doc.

When I follow the instructions I see in the new DEVELOPMENT.md it seems to install Contour but nothing else, and while the tests "run" there are no tests so I'm unclear what the purpose of that was. Is there no `net-ingressv2` controller that translates KIngress objects into Gateway API objects? 

I've tried installing the Serving CRDs and Core, but the KIngress object is never reconciled which makes me think a `net-ingressv2` or similar controller is still needed.

**Comment by nak3** [comment]
Hi @XanderStrike,
No, net-ingressv2 repo does tests for Gateway API resources and so it is different from net-istio, net-kourier and serving. It is similar to [networking repo's conformance test](https://github.com/knative/networking/tree/main/test/conformance/ingress).

Sering repo will add the controller but it is currently blocked by k8s lib v1.20 update.

> while the tests "run" there are no tests so I'm unclear what the purpose of that was.

Sorry, I found my dypo. The line `go test` needs to be:

```
go test -v -tags=e2e -count=1  ./test/conformance/ingressv2/  -run "TestIngressConformance/basics" \
```

I will fix it or it would be great if you could send the PR.

**Comment by XanderStrike** [comment]
Okay sweet, the fact that it's blocked is sufficient for my needs right now, we can put a pin in this and come back when it's unblocked.

> For controller, Serving repo will add the controller but it is currently blocked by k8s lib v1.20 update

Do you have a link to somewhere I can track the work of the controller? Once it's unblocked, I'd like to be able to try it out and I know recognize this repo isn't the place to look.

**Comment by nak3** [comment]
> Do you have a link to somewhere I can track the work of the controller? Once it's unblocked, I'd like to be able to try it out and I know recognize this repo isn't the place to look.

Sure, current tracker is here https://github.com/knative/serving/issues/11325
